### ISSUE TITLE
Error while running convert_to_spadl (tutorial1)

### ISSUE THREAD

**Issue by ferbel333** [soccer-analytics-research/fot-valuing-actions#1]
Good evening, I am getting an error while running "convert_to_spadl('wyscout.h5', 'spadl.h5') in tutorial1, both offline and in Google Colab.
Thank you very much for your help and for helping the tracking community. Best regards. Fernando
.-.
ERROR:
convert_to_spadl('wyscout.h5', 'spadl.h5')

...Inserting actiontypes
...Inserting bodyparts
...Inserting results
...Converting games
...Converting players
...Converting teams
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-27-47a193417562> in <module>()
----> 1 convert_to_spadl('wyscout.h5', 'spadl.h5')

2 frames
/usr/local/lib/python3.6/dist-packages/pandas/io/pytables.py in get(self, key)
    789             group = self.get_node(key)
    790             if group is None:
--> 791                 raise KeyError(f"No object named {key} in the file")
    792             return self._read_group(group)
    793 

KeyError: 'No object named teams in the file'

**Comment by JanVanHaaren** [comment]
Thanks for your interest in the tutorial, Fernando! I am unfortunately unable to reproduce this issue. I have successfully run the notebook in Google Colab without making any changes to the code besides uncommenting the lines at the top that install `tables` and `socceraction`.

Did you make any changes to the code yourself prior to executing the notebook?

**Comment by mike-stn** [comment]
Hi Fernando, hi Jan,

unfortunately I get the same error running it in Spyder. I also checked the socceraction/spadl/wyscout.py file where the convert_to_spadl function should be, but couldn't find it! 

Could it be, that you removed/renamed it?

Best,
Mike

**Comment by JanVanHaaren** [comment]
Thanks, Mike. Which version of `socceraction` have you installed? The maintainers of the `socceraction` package recently re-organized the code in their package. As a result, the notebooks are no longer compatible with the latest version. However, the notebooks should still be compatible with the version that is mentioned in the notebooks.

**Comment by mike-stn** [comment]
Thanks Jan, this did the trick for me! :-)
