### ISSUE TITLE
Error while running 'train classifiers' in tutorial 3

### ISSUE THREAD

**Issue by ClaudioHHS** [soccer-analytics-research/fot-valuing-actions#2]
I get this error if i run the 'train classifier' code from tutorial 3 in Google Colab:

KeyError: "None of [Index(['start_distance_to_goal-0', 'end_distance_to_goal-0',\n       'start_distance_to_goal-1', 'end_distance_to_goal-1',\n       'start_distance_to_goal-2', 'end_distance_to_goal-2',\n       'start_angle_to_goal-0', 'end_angle_to_goal-0', 'start_angle_to_goal-1',\n       'end_angle_to_goal-1', 'start_angle_to_goal-2', 'end_angle_to_goal-2',\n       'team-1', 'team-2', 'result_id-0', 'result_id-1', 'result_id-2'],\n      dtype='object')] are in the [columns]"

I have run the codes from all the tutorials multiple times and tried different things but i can't find the solution. What is the solution?

Thank you in advance!

**Comment by JanVanHaaren** [comment]
Thanks for your interest in the notebooks, Claudio!

The feature names appear to be incompatible with the feature names in the earlier notebooks. I will update the notebook.

You will likely need to use the following feature names in your notebook:

`features = [
    'start_distance_to_goal-0',
    'end_distance_to_goal-0',
    'start_distance_to_goal-1',
    'end_distance_to_goal-1',
    'start_distance_to_goal-2',
    'end_distance_to_goal-2',
    'start_angle_to_goal-0',
    'end_angle_to_goal-0',
    'start_angle_to_goal-1',
    'end_angle_to_goal-1',
    'start_angle_to_goal-2',
    'end_angle_to_goal-2',
    'team-1',
    'team-2'
]`
